swagger: '2.0'
produces:
  - application/json
paths:
  '/repositories/{owner}/{repository-name}':
    get:
      description: Get repository.
      parameters:
        - description: Name of repository owner.
          in: path
          name: owner
          required: true
          type: string
        - description: Name of repository.
          in: path
          name: repository-name
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/repo'
        '403':
          description: |
            API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
            for details.
definitions:
  repo:
    properties:
      fullName:
        type: string
      description:
        type: string
      cloneUrl:
        type: string
      stars:
        type: integer
      createdAt:
        description: 'ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ'
        type: string
    type: object
